/*
Beckn Protocol Meta API

This document contains all the meta API endpoints that are implemented by the network participants. The information returned from these endpoints typically contain cacheable information.

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meta

import (
	"encoding/json"
	"time"
)

// checks if the Context type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Context{}

// Context Every API call in beckn protocol has a context. It provides a high-level overview to the receiver about the nature of the intended transaction. Typically, it is the BAP that sets the transaction context based on the consumer's location and action on their UI. But sometimes, during unsolicited callbacks, the BPP also sets the transaction context but it is usually the same as the context of a previous full-cycle, request-callback interaction between the BAP and the BPP. The context object contains four types of fields. <ol><li>Demographic information about the transaction using fields like `domain`, `country`, and `region`.</li><li>Addressing details like the sending and receiving platform's ID and API URL.</li><li>Interoperability information like the protocol version that implemented by the sender and,</li><li>Transaction details like the method being called at the receiver's endpoint, the transaction_id that represents an end-to-end user session at the BAP, a message ID to pair requests with callbacks, a timestamp to capture sending times, a ttl to specifiy the validity of the request, and a key to encrypt information if necessary.</li></ol> This object must be passed in every interaction between a BAP and a BPP. In HTTP/S implementations, it is not necessary to send the context during the synchronous response. However, in asynchronous protocols, the context must be sent during all interactions,
type Context struct {
	// Domain code that is relevant to this transaction context
	Domain interface{} `json:"domain,omitempty"`
	// The location where the transaction is intended to be fulfilled.
	Location *Location `json:"location,omitempty"`
	// The Beckn protocol method being called by the sender and executed at the receiver.
	Action *string `json:"action,omitempty"`
	// Version of transaction protocol being used by the sender.
	Version *string `json:"version,omitempty"`
	// Subscriber ID of the BAP
	BapId *string `json:"bap_id,omitempty"`
	// Subscriber URL of the BAP for accepting callbacks from BPPs.
	BapUri *string `json:"bap_uri,omitempty"`
	// Subscriber ID of the BPP
	BppId *string `json:"bpp_id,omitempty"`
	// Subscriber URL of the BPP for accepting calls from BAPs.
	BppUri *string `json:"bpp_uri,omitempty"`
	// This is a unique value which persists across all API calls from `search` through `confirm`. This is done to indicate an active user session across multiple requests. The BPPs can use this value to push personalized recommendations, and dynamic offerings related to an ongoing transaction despite being unaware of the user active on the BAP.
	TransactionId *string `json:"transaction_id,omitempty"`
	// This is a unique value which persists during a request / callback cycle. Since beckn protocol APIs are asynchronous, BAPs need a common value to match an incoming callback from a BPP to an earlier call. This value can also be used to ignore duplicate messages coming from the BPP. It is recommended to generate a fresh message_id for every new interaction. When sending unsolicited callbacks, BPPs must generate a new message_id.
	MessageId *string `json:"message_id,omitempty"`
	// Time of request generation in RFC3339 format
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// The encryption public key of the sender
	Key *string `json:"key,omitempty"`
	// The duration in ISO8601 format after timestamp for which this message holds valid
	Ttl *string `json:"ttl,omitempty"`
}

// NewContext instantiates a new Context object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContext() *Context {
	this := Context{}
	return &this
}

// NewContextWithDefaults instantiates a new Context object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContextWithDefaults() *Context {
	this := Context{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Context) GetDomain() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Context) GetDomainOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return &o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *Context) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given interface{} and assigns it to the Domain field.
func (o *Context) SetDomain(v interface{}) {
	o.Domain = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Context) GetLocation() Location {
	if o == nil || IsNil(o.Location) {
		var ret Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetLocationOk() (*Location, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Context) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Location and assigns it to the Location field.
func (o *Context) SetLocation(v Location) {
	o.Location = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *Context) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *Context) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *Context) SetAction(v string) {
	o.Action = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Context) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Context) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Context) SetVersion(v string) {
	o.Version = &v
}

// GetBapId returns the BapId field value if set, zero value otherwise.
func (o *Context) GetBapId() string {
	if o == nil || IsNil(o.BapId) {
		var ret string
		return ret
	}
	return *o.BapId
}

// GetBapIdOk returns a tuple with the BapId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetBapIdOk() (*string, bool) {
	if o == nil || IsNil(o.BapId) {
		return nil, false
	}
	return o.BapId, true
}

// HasBapId returns a boolean if a field has been set.
func (o *Context) HasBapId() bool {
	if o != nil && !IsNil(o.BapId) {
		return true
	}

	return false
}

// SetBapId gets a reference to the given string and assigns it to the BapId field.
func (o *Context) SetBapId(v string) {
	o.BapId = &v
}

// GetBapUri returns the BapUri field value if set, zero value otherwise.
func (o *Context) GetBapUri() string {
	if o == nil || IsNil(o.BapUri) {
		var ret string
		return ret
	}
	return *o.BapUri
}

// GetBapUriOk returns a tuple with the BapUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetBapUriOk() (*string, bool) {
	if o == nil || IsNil(o.BapUri) {
		return nil, false
	}
	return o.BapUri, true
}

// HasBapUri returns a boolean if a field has been set.
func (o *Context) HasBapUri() bool {
	if o != nil && !IsNil(o.BapUri) {
		return true
	}

	return false
}

// SetBapUri gets a reference to the given string and assigns it to the BapUri field.
func (o *Context) SetBapUri(v string) {
	o.BapUri = &v
}

// GetBppId returns the BppId field value if set, zero value otherwise.
func (o *Context) GetBppId() string {
	if o == nil || IsNil(o.BppId) {
		var ret string
		return ret
	}
	return *o.BppId
}

// GetBppIdOk returns a tuple with the BppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetBppIdOk() (*string, bool) {
	if o == nil || IsNil(o.BppId) {
		return nil, false
	}
	return o.BppId, true
}

// HasBppId returns a boolean if a field has been set.
func (o *Context) HasBppId() bool {
	if o != nil && !IsNil(o.BppId) {
		return true
	}

	return false
}

// SetBppId gets a reference to the given string and assigns it to the BppId field.
func (o *Context) SetBppId(v string) {
	o.BppId = &v
}

// GetBppUri returns the BppUri field value if set, zero value otherwise.
func (o *Context) GetBppUri() string {
	if o == nil || IsNil(o.BppUri) {
		var ret string
		return ret
	}
	return *o.BppUri
}

// GetBppUriOk returns a tuple with the BppUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetBppUriOk() (*string, bool) {
	if o == nil || IsNil(o.BppUri) {
		return nil, false
	}
	return o.BppUri, true
}

// HasBppUri returns a boolean if a field has been set.
func (o *Context) HasBppUri() bool {
	if o != nil && !IsNil(o.BppUri) {
		return true
	}

	return false
}

// SetBppUri gets a reference to the given string and assigns it to the BppUri field.
func (o *Context) SetBppUri(v string) {
	o.BppUri = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *Context) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *Context) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *Context) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *Context) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *Context) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *Context) SetMessageId(v string) {
	o.MessageId = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *Context) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *Context) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *Context) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *Context) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *Context) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *Context) SetKey(v string) {
	o.Key = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *Context) GetTtl() string {
	if o == nil || IsNil(o.Ttl) {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Context) GetTtlOk() (*string, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *Context) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the Ttl field.
func (o *Context) SetTtl(v string) {
	o.Ttl = &v
}

func (o Context) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Context) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.BapId) {
		toSerialize["bap_id"] = o.BapId
	}
	if !IsNil(o.BapUri) {
		toSerialize["bap_uri"] = o.BapUri
	}
	if !IsNil(o.BppId) {
		toSerialize["bpp_id"] = o.BppId
	}
	if !IsNil(o.BppUri) {
		toSerialize["bpp_uri"] = o.BppUri
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.MessageId) {
		toSerialize["message_id"] = o.MessageId
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

type NullableContext struct {
	value *Context
	isSet bool
}

func (v NullableContext) Get() *Context {
	return v.value
}

func (v *NullableContext) Set(val *Context) {
	v.value = val
	v.isSet = true
}

func (v NullableContext) IsSet() bool {
	return v.isSet
}

func (v *NullableContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContext(val *Context) *NullableContext {
	return &NullableContext{value: val, isSet: true}
}

func (v NullableContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


