/*
Beckn Protocol Meta API

This document contains all the meta API endpoints that are implemented by the network participants. The information returned from these endpoints typically contain cacheable information.

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meta

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReturnReasons type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReturnReasons{}

// ReturnReasons struct for ReturnReasons
type ReturnReasons struct {
	Context ReturnReasonsContext `json:"context"`
	Message ReturnReasonsMessage `json:"message"`
}

type _ReturnReasons ReturnReasons

// NewReturnReasons instantiates a new ReturnReasons object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnReasons(context ReturnReasonsContext, message ReturnReasonsMessage) *ReturnReasons {
	this := ReturnReasons{}
	this.Context = context
	this.Message = message
	return &this
}

// NewReturnReasonsWithDefaults instantiates a new ReturnReasons object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnReasonsWithDefaults() *ReturnReasons {
	this := ReturnReasons{}
	return &this
}

// GetContext returns the Context field value
func (o *ReturnReasons) GetContext() ReturnReasonsContext {
	if o == nil {
		var ret ReturnReasonsContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *ReturnReasons) GetContextOk() (*ReturnReasonsContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *ReturnReasons) SetContext(v ReturnReasonsContext) {
	o.Context = v
}

// GetMessage returns the Message field value
func (o *ReturnReasons) GetMessage() ReturnReasonsMessage {
	if o == nil {
		var ret ReturnReasonsMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ReturnReasons) GetMessageOk() (*ReturnReasonsMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ReturnReasons) SetMessage(v ReturnReasonsMessage) {
	o.Message = v
}

func (o ReturnReasons) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReturnReasons) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ReturnReasons) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReturnReasons := _ReturnReasons{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReturnReasons)

	if err != nil {
		return err
	}

	*o = ReturnReasons(varReturnReasons)

	return err
}

type NullableReturnReasons struct {
	value *ReturnReasons
	isSet bool
}

func (v NullableReturnReasons) Get() *ReturnReasons {
	return v.value
}

func (v *NullableReturnReasons) Set(val *ReturnReasons) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnReasons) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnReasons) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnReasons(val *ReturnReasons) *NullableReturnReasons {
	return &NullableReturnReasons{value: val, isSet: true}
}

func (v NullableReturnReasons) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnReasons) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


