/*
Beckn Protocol Meta API

This document contains all the meta API endpoints that are implemented by the network participants. The information returned from these endpoints typically contain cacheable information.

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meta

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetReturnReasons type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReturnReasons{}

// GetReturnReasons struct for GetReturnReasons
type GetReturnReasons struct {
	Context GetReturnReasonsContext `json:"context"`
}

type _GetReturnReasons GetReturnReasons

// NewGetReturnReasons instantiates a new GetReturnReasons object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReturnReasons(context GetReturnReasonsContext) *GetReturnReasons {
	this := GetReturnReasons{}
	this.Context = context
	return &this
}

// NewGetReturnReasonsWithDefaults instantiates a new GetReturnReasons object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReturnReasonsWithDefaults() *GetReturnReasons {
	this := GetReturnReasons{}
	return &this
}

// GetContext returns the Context field value
func (o *GetReturnReasons) GetContext() GetReturnReasonsContext {
	if o == nil {
		var ret GetReturnReasonsContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *GetReturnReasons) GetContextOk() (*GetReturnReasonsContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *GetReturnReasons) SetContext(v GetReturnReasonsContext) {
	o.Context = v
}

func (o GetReturnReasons) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReturnReasons) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	return toSerialize, nil
}

func (o *GetReturnReasons) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetReturnReasons := _GetReturnReasons{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetReturnReasons)

	if err != nil {
		return err
	}

	*o = GetReturnReasons(varGetReturnReasons)

	return err
}

type NullableGetReturnReasons struct {
	value *GetReturnReasons
	isSet bool
}

func (v NullableGetReturnReasons) Get() *GetReturnReasons {
	return v.value
}

func (v *NullableGetReturnReasons) Set(val *GetReturnReasons) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReturnReasons) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReturnReasons) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReturnReasons(val *GetReturnReasons) *NullableGetReturnReasons {
	return &NullableGetReturnReasons{value: val, isSet: true}
}

func (v NullableGetReturnReasons) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReturnReasons) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


