/*
Beckn Protocol Core

Beckn Core Transaction API specification

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package transaction

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Confirm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Confirm{}

// Confirm struct for Confirm
type Confirm struct {
	Context ConfirmContext `json:"context"`
	Message SelectMessage `json:"message"`
}

type _Confirm Confirm

// NewConfirm instantiates a new Confirm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirm(context ConfirmContext, message SelectMessage) *Confirm {
	this := Confirm{}
	this.Context = context
	this.Message = message
	return &this
}

// NewConfirmWithDefaults instantiates a new Confirm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmWithDefaults() *Confirm {
	this := Confirm{}
	return &this
}

// GetContext returns the Context field value
func (o *Confirm) GetContext() ConfirmContext {
	if o == nil {
		var ret ConfirmContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *Confirm) GetContextOk() (*ConfirmContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *Confirm) SetContext(v ConfirmContext) {
	o.Context = v
}

// GetMessage returns the Message field value
func (o *Confirm) GetMessage() SelectMessage {
	if o == nil {
		var ret SelectMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Confirm) GetMessageOk() (*SelectMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Confirm) SetMessage(v SelectMessage) {
	o.Message = v
}

func (o Confirm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Confirm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Confirm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfirm := _Confirm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfirm)

	if err != nil {
		return err
	}

	*o = Confirm(varConfirm)

	return err
}

type NullableConfirm struct {
	value *Confirm
	isSet bool
}

func (v NullableConfirm) Get() *Confirm {
	return v.value
}

func (v *NullableConfirm) Set(val *Confirm) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirm) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirm(val *Confirm) *NullableConfirm {
	return &NullableConfirm{value: val, isSet: true}
}

func (v NullableConfirm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


