/*
Beckn Protocol Core

Beckn Core Transaction API specification

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package transaction

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Rating2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Rating2{}

// Rating2 struct for Rating2
type Rating2 struct {
	Context Rating2Context `json:"context"`
	Message Rating2Message `json:"message"`
}

type _Rating2 Rating2

// NewRating2 instantiates a new Rating2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRating2(context Rating2Context, message Rating2Message) *Rating2 {
	this := Rating2{}
	this.Context = context
	this.Message = message
	return &this
}

// NewRating2WithDefaults instantiates a new Rating2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRating2WithDefaults() *Rating2 {
	this := Rating2{}
	return &this
}

// GetContext returns the Context field value
func (o *Rating2) GetContext() Rating2Context {
	if o == nil {
		var ret Rating2Context
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *Rating2) GetContextOk() (*Rating2Context, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *Rating2) SetContext(v Rating2Context) {
	o.Context = v
}

// GetMessage returns the Message field value
func (o *Rating2) GetMessage() Rating2Message {
	if o == nil {
		var ret Rating2Message
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Rating2) GetMessageOk() (*Rating2Message, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Rating2) SetMessage(v Rating2Message) {
	o.Message = v
}

func (o Rating2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Rating2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Rating2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRating2 := _Rating2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRating2)

	if err != nil {
		return err
	}

	*o = Rating2(varRating2)

	return err
}

type NullableRating2 struct {
	value *Rating2
	isSet bool
}

func (v NullableRating2) Get() *Rating2 {
	return v.value
}

func (v *NullableRating2) Set(val *Rating2) {
	v.value = val
	v.isSet = true
}

func (v NullableRating2) IsSet() bool {
	return v.isSet
}

func (v *NullableRating2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRating2(val *Rating2) *NullableRating2 {
	return &NullableRating2{value: val, isSet: true}
}

func (v NullableRating2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRating2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


