/*
Beckn Protocol Core

Beckn Core Transaction API specification

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package transaction

import (
	"encoding/json"
)

// checks if the ItemQuantityMinimum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemQuantityMinimum{}

// ItemQuantityMinimum This represents the minimum quantity allowed for purchase of the item
type ItemQuantityMinimum struct {
	Count *int32 `json:"count,omitempty"`
	Measure *Scalar `json:"measure,omitempty"`
}

// NewItemQuantityMinimum instantiates a new ItemQuantityMinimum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemQuantityMinimum() *ItemQuantityMinimum {
	this := ItemQuantityMinimum{}
	return &this
}

// NewItemQuantityMinimumWithDefaults instantiates a new ItemQuantityMinimum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemQuantityMinimumWithDefaults() *ItemQuantityMinimum {
	this := ItemQuantityMinimum{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ItemQuantityMinimum) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemQuantityMinimum) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ItemQuantityMinimum) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ItemQuantityMinimum) SetCount(v int32) {
	o.Count = &v
}

// GetMeasure returns the Measure field value if set, zero value otherwise.
func (o *ItemQuantityMinimum) GetMeasure() Scalar {
	if o == nil || IsNil(o.Measure) {
		var ret Scalar
		return ret
	}
	return *o.Measure
}

// GetMeasureOk returns a tuple with the Measure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemQuantityMinimum) GetMeasureOk() (*Scalar, bool) {
	if o == nil || IsNil(o.Measure) {
		return nil, false
	}
	return o.Measure, true
}

// HasMeasure returns a boolean if a field has been set.
func (o *ItemQuantityMinimum) HasMeasure() bool {
	if o != nil && !IsNil(o.Measure) {
		return true
	}

	return false
}

// SetMeasure gets a reference to the given Scalar and assigns it to the Measure field.
func (o *ItemQuantityMinimum) SetMeasure(v Scalar) {
	o.Measure = &v
}

func (o ItemQuantityMinimum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemQuantityMinimum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Measure) {
		toSerialize["measure"] = o.Measure
	}
	return toSerialize, nil
}

type NullableItemQuantityMinimum struct {
	value *ItemQuantityMinimum
	isSet bool
}

func (v NullableItemQuantityMinimum) Get() *ItemQuantityMinimum {
	return v.value
}

func (v *NullableItemQuantityMinimum) Set(val *ItemQuantityMinimum) {
	v.value = val
	v.isSet = true
}

func (v NullableItemQuantityMinimum) IsSet() bool {
	return v.isSet
}

func (v *NullableItemQuantityMinimum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemQuantityMinimum(val *ItemQuantityMinimum) *NullableItemQuantityMinimum {
	return &NullableItemQuantityMinimum{value: val, isSet: true}
}

func (v NullableItemQuantityMinimum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemQuantityMinimum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


