/*
Beckn Protocol Core

Beckn Core Transaction API specification

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package transaction

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Init type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Init{}

// Init struct for Init
type Init struct {
	Context InitContext `json:"context"`
	Message SelectMessage `json:"message"`
}

type _Init Init

// NewInit instantiates a new Init object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInit(context InitContext, message SelectMessage) *Init {
	this := Init{}
	this.Context = context
	this.Message = message
	return &this
}

// NewInitWithDefaults instantiates a new Init object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitWithDefaults() *Init {
	this := Init{}
	return &this
}

// GetContext returns the Context field value
func (o *Init) GetContext() InitContext {
	if o == nil {
		var ret InitContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *Init) GetContextOk() (*InitContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *Init) SetContext(v InitContext) {
	o.Context = v
}

// GetMessage returns the Message field value
func (o *Init) GetMessage() SelectMessage {
	if o == nil {
		var ret SelectMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Init) GetMessageOk() (*SelectMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Init) SetMessage(v SelectMessage) {
	o.Message = v
}

func (o Init) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Init) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Init) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInit := _Init{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInit)

	if err != nil {
		return err
	}

	*o = Init(varInit)

	return err
}

type NullableInit struct {
	value *Init
	isSet bool
}

func (v NullableInit) Get() *Init {
	return v.value
}

func (v *NullableInit) Set(val *Init) {
	v.value = val
	v.isSet = true
}

func (v NullableInit) IsSet() bool {
	return v.isSet
}

func (v *NullableInit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInit(val *Init) *NullableInit {
	return &NullableInit{value: val, isSet: true}
}

func (v NullableInit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


